---
title: "Resultados \n Saber 11"
author: "Manuel Rodriguez"
params:
   codigo:
    label: "Codigo"
    value: !r format(datos$cole_cod_dane_sede[1], scientific =FALSE )
    input: numeric	
output: 
  ioslides_presentation: 
  css: styles.css
---

```{r, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE, fig.align="center")

numero <- params$codigo

make <- datos$cole_nombre_sede[datos$cole_cod_dane_sede == params$codigo][1]

make <- make[1]

datos$cole<-ifelse(datos$cole_nombre_sede == make,1,0)
```

##  SEDE: `r make ` 

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align="center")


datos$cole<-ifelse(datos$cole_nombre_sede == make,1,0)

datos$muni<-ifelse(datos$cole_mcpio_ubicacion == 
                     datos$cole_mcpio_ubicacion[datos$cole == 1][1],1,0)

datos$muni <- ifelse(datos$cole == 1, 0 , datos$muni)

datos$dep<-ifelse(datos$cole_depto_ubicacion == 
                    datos$cole_depto_ubicacion[datos$muni == 1][1],1,0)

mscore <-  datos[datos$cole == 1,]  %>% 
  summarise(mat = mean(punt_matematicas),
            len = mean(punt_lectura_critica),
            nat = mean(punt_c_naturales),
            soc = mean(punt_sociales_ciudadanas),
            est = n())

col <- make

puntaje <- data.frame(mat = datos$punt_matematicas,
                      lec = datos$punt_lectura_critica,
                      nat = datos$punt_c_naturales,
                      soc = datos$punt_sociales_ciudadanas,
                      cole = datos$cole, genero = datos$estu_genero,
                      muni = datos$muni, estrato = datos$fami_estratovivienda,
                      dep = datos$dep,
                      edu = datos$fami_educacionmadre,
                      inse = datos$estu_inse_individual
                      )
```

```{r,fig.width = 7, fig.height = 3.5,echo= FALSE, warning=FALSE}

t_punt<-reshape(puntaje[puntaje$dep == 1,],direction = "long" , v.names = "punt_",varying = list(1:4))

t_punt$prueba<-ifelse(t_punt$time == 1,"Matematicas",ifelse(t_punt$time == 2,"Lectura", ifelse(t_punt$time == 3,"Naturales", ifelse(t_punt$time == 4,"Sociales",""))))

t_punt$Pruebas <- t_punt$prueba

ggplot(data = t_punt[t_punt$cole == 1,],aes(x=prueba , y = punt_)) + 
  geom_violin(aes(group = time, fill = Pruebas),trim = FALSE) + geom_boxplot(width = 0.2) + xlab(" ") + ylab("Puntaje") + theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) + theme_minimal() +theme(legend.position = c("bottom")) + ggtitle("Distribution Puntajes") + coord_cartesian(ylim = c(0, 100))

```
